[package]
name = "csbind"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
csbindgen = "1.9.3"
bitflags = "2.1.0"

[build-dependencies]
cc = "1.0.79"
bindgen = "0.69.4"
csbindgen = "1.9.3"